import { Tabs } from "../components/client";
import { TopMenu, Button } from "../components/server";
import Link from "next/link";
import Image from "next/image";

export const metadata = {
  title: "Yask",
  description: "Generated by Next.js",
};

export default function WorksLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  return (
    <>
      <TopMenu />
      <header id="header" className="container">
        <hgroup className="text-center ">
          <Image
            className="inline-block mb-6 "
            src="yask-logo.svg"
            width={64}
            height={64}
            alt="Yask Design"
          />
          <h1 className="text-2xl mb-6 text-yask">
            Hi! We Do Web & App Design
            <br /> Icons Sets, Frontend
          </h1>
        </hgroup>
      </header>
      <nav className="container z-10 text-center mb-10 sticky top-8">
        <Tabs />
      </nav>
      {children}
    </>
  );
}
