import "../styles/globals.css";
import { Inter, Roboto_Mono } from "@next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto_mono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// END FONT

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
      <body className="bg-ybg text-yask" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
