import { ArticleTopMenu } from "../components/server";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function WorkLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ArticleTopMenu />
      <div className="container">{children}</div>
    </>
  );
}
