import {
  ArticleTopMenu,
  Footer,
  ArticleSubMenu,
  Article,
} from "../components/server";
// export const metadata = {
//   title: "",
//   description: "Generated by Next.js",
// };

export default function WorkLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ArticleTopMenu />

      {children}
      <Footer />
    </>
  );
}
