import { WorkHeader, WorkFooter } from "../components/main";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function WorkLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <WorkHeader />
      <div className="container">{children}</div>
      <WorkFooter />
    </div>
  );
}
